module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_BASE_URL || "https://www.vlinkinfo.com",
  generateRobotsTxt: true,
  generateIndexSitemap: false,
  exclude: [
    "/technologies",
    "/re-engineering-legacy-products-and-apps",
    "/dedicated-teams",
    "/internet-of-things-iot",
    "/corporate-social-responsibility",
    "/industries/banking-financial-services",
    "/whitepapers",
    "/about/our-leadership-team",
    "/technologies/hire-backend-developers-engineers",
    "/cloud-managed-infrastructure-services",
    "/case-studies",
    "/cloud-devops-automation-services",
    "/webinars",
    "/technologies/hire-front-end-developers-web-mobile",
    "/technologies/hire-net-developers-programmers",
    "/mobile-app-development",
    "/web-development-company-in-massachusetts",
    "/digital-transformation-services",
    "/contact",
    "/nearshore-software-development",
    "/podcast",
    "/technologies/hire-react-developers-app-programmers",
    "/brochures",
    "/subscribe",
    "/technologies/hire-full-stack-developers-software-engineers-guide",
    "/case-study/smart-shopping-cart-android-based-application",
    "/offshore-software-development-outsourcing-hiring",
    "/technologies/hire-nodejs-developers",
    "/news",
    "/it-staffing-services-in-massachusetts",
    "/data-analytics",
    "/technologies/hire-java-developers",
    "/software-maintenance-support-services",
    "/qa-software-testing-services",
    "/it-staff-augmentation",
    "/custom-software-development",
    "/it-staffing-services-in-connecticut",
    "/about",
    "/product-engineering",
    "/process",
    "/faq",
    "/machine-learning-ai-development",
    "/data-analytics-engineering-in-massachusetts",
    "/technologies/hire-full-stack-developers-software-engineers-guide",
    "/technologies/hire-python-developers-engineers",
    "/technologies/hire-angular-developers",
    "/technologies/hire-java-developers",
    "/case-studies",
    "/technologies/hire-angular-developers",
    "/whitepaper/legacy-system-modernization-and-observability",
    "/education-industry",
    "/re-engineering-legacy-products-and-apps",
    "/dedicated-teams",
    "/it-staffing-services",
    "/custom-software-development",
    "/it-consulting",
    "/digital-experience-engineering/mobility",
    "/digital-experience-engineering",
    "/cookie-policy",
    "/privacy",
    "/team/nitin-nijhawan",
    "/team/sharad-patney",
    "/team/vanitha-patil",
    "/team/tracy-gardner",
    "/team/doreen-pereira",
    "/team/manish-jangid",
    "/team/jagdish-dalal",
    "/team/carl-r-johnson",
    "/cookie-policy",
    "/it-staffing-services-in-connecticut",
    "/nearshore-software-development",
    "/case-studies/soa-integration-services",
    "/case-studies/sepsis-prediction",
    "/simplyedi-book-demo",
    "/case-studies/auto-parts-smart-sales-application",
    "/technologies/hire-flutter-app-developers",
    "/data-analytics",
    "/technologies/hire-angular-developers",
    "/web-development-services",
    "/technologies/hire-full-stack-developers-software-engineers-guide",
    "/simplyedi",
    "/success-stories",
    "/vlinkcare-online-telemedicine-software",
    "/solutions",
    "/it-staffing-services",
    "/technologies/nearshore-software-development",
    "/webinar",
    "/resources",
    "/cookie-policy",
    "/devops-automation-development-company",
    "/technologies/offshore-software-development-outsourcing-hiring",
    "/digital-experience-engineering/web-development-services",
    "/services/strategic-workforce-management",
    "/careers",
    "/cloud-migration-services",
    "/qa-testing-service",
    "/fasthire-staffing-solutions",
    "/in-en/intranet-portal",
    "/cloud-cost-optimization",
    "/services/digital-transformation",
    "/blog/evolution-of-outsourcing-to-current-and-future-trends",
    "/services/information-management",
    "/vlink-careers",
    "/in-en/open-source-solutions",
    "/data-analytics/data-engineering-visualization",
    "/microsoft-azure-cloud-services",
    "/digital-experience-engineering/web-development",
    "/services/app-development-maintenance",
    "/in-en",
    "/cloud-migration-services",
    "/data-analytics/web-mobile-digital-analytics",
    "/banking-financial-services",
    "/in-en/ibm-solutions",
    "/cloud-migration-healthcare-insurance-industry",
    "/privacy",
    "/digital-experience-engineering/web-development",
    "/aws-cloud-services",
    "/in-en/crm-mobile-way",
    "/careers-in-india",
    // "/in-en/content-publishing-system",
    "/vlinkcare-book-demo",
    "/consulting-service",
    "/whitepaper/artificial-intelligence-machine-learning-envisioning-the-future",
    "/how-digital-technologies-are-improving-patient-experience",
    "/aws-cloud-services",
    "/newsroom/vlink-inc-expands-apac-executive-team-with-key-new-hire",
    "/digital-experience-engineering/web-development",
    "/company-news",
    "/onshore-vs-offshore-outsourcing",
    "/careers",
    "/blog/retail-tech-trends-2018",
    "/web-mobile-digital-analytics",
    "/vlink-inc-expands-apac-executive-team-with-key-new-hire",
    "/web-mobile-digital-analytics",
    "/technologies/hire-front-end-developers-web-mobile",
    "/ibm-solutions",
    "/enterprise-business-solutions",
    "/data-engineering-visualization",
    "/crm-mobile-way",
    // "/content-publishing-system",
    "/web-development",
    "/top-9-retail-tech-trends-to-watch"
  ],
  robotsTxtOptions: {
    policies: [
      {
        userAgent: "*",
        disallow: [
          " /blog/*?s=",
          " /blog/category/*",
          " /blog/tag/*",
          " /blog/page/*",
          " /author/vlink/*",
          " */tag/*",
          " /wp-content/uploads/*",
          " *?p=",
          " */?job=",
          " *?swcfpc=",
          " *?trk",
          " */feed",
          " /blog/2015/*",
          " /blog/2016/*",
          " /blog/2017/*",
          " /blog/2018/*",
          " /blog/2019/*",
          " /blog/2020/*",
          " /blog/2021/*",
          " /blog/2022/*",
          " /blog/2023/*",
          " */?ref=",
        ],
      },
    ],
  },
};
