export const countries =  [ 
    { value: "Select Country", name: "Select Country"}, 
    { value: "United States", name: "United States"}, 
    { value: "Afghanistan", name: "Afghanistan"}, 
    { value: "Albania", name: "Albania"}, 
    { value: "Algeria", name: "Algeria"}, 
    { value: "Andorra", name: "Andorra"}, 
    { value: "Angola", name: "Angola"}, 
    { value: "Antigua and Barbuda", name: "Antigua and Barbuda"}, 
    { value: "Argentina", name: "Argentina"}, 
    { value: "Armenia", name: "Armenia"}, 
    { value: "Australia", name: "Australia"}, 
    { value: "Austria", name: "Austria"}, 
    { value: "Azerbaijan", name: "Azerbaijan"}, 
    { value: "Bahamas", name: "Bahamas"}, 
    { value: "Bahrain", name: "Bahrain"}, 
    { value: "Bangladesh", name: "Bangladesh"}, 
    { value: "Barbados", name: "Barbados"}, 
    { value: "Belarus", name: "Belarus"}, 
    { value: "Belgium", name: "Belgium"}, 
    { value: "Belize", name: "Belize"}, 
    { value: "Country", name: "Country"}, 
    { value: "Executive", name: "Executive"}, 
    { value: "Benin", name: "Benin"}, 
    { value: "Bhutan", name: "Bhutan"}, 
    { value: "Bolivia", name: "Bolivia"}, 
    { value: "Bosnia and Herzegovina", name: "Bosnia and Herzegovina"}, 
    { value: "Botswana", name: "Botswana"}, 
    { value: "Brazil", name: "Brazil"}, 
    { value: "Brunei", name: "Brunei"}, 
    { value: "Bulgaria", name: "Bulgaria"}, 
    { value: "Burkina Faso", name: "Burkina Faso"}, 
    { value: "Burundi", name: "Burundi"}, 
    { value: "Cabo Verde", name: "Cabo Verde"}, 
    { value: "Cambodia", name: "Cambodia"}, 
    { value: "Cameroon", name: "Cameroon"}, 
    { value: "Canada", name: "Canada"}, 
    { value: "Central African Republic (CAR)", name: "Central African Republic (CAR)"}, 
    { value: "Chad", name: "Chad"}, 
    { value: "Chile", name: "Chile"}, 
    { value: "China", name: "China"}, 
    { value: "Colombia", name: "Colombia"}, 
    { value: "Comoros", name: "Comoros"}, 
    { value: "Democratic Republic of the Congo", name: "Democratic Republic of the Congo"}, 
    { value: "Republic of the Congo", name: "Republic of the Congo"}, 
    { value: "Costa Rica", name: "Costa Rica"}, 
    { value: "Cote d'Ivoire", name: "Cote d'Ivoire"}, 
    { value: "Croatia", name: "Croatia"}, 
    { value: "Cuba", name: "Cuba"}, 
    { value: "Cyprus", name: "Cyprus"}, 
    { value: "Czech Republic", name: "Czech Republic"}, 
    { value: "Denmark", name: "Denmark"}, 
    { value: "Djibouti", name: "Djibouti"}, 
    { value: "Dominica", name: "Dominica"}, 
    { value: "Dominican Republic", name: "Dominican Republic"}, 
    { value: "Ecuador", name: "Ecuador"}, 
    { value: "Egypt", name: "Egypt"}, 
    { value: "El Salvador", name: "El Salvador"}, 
    { value: "Equatorial Guinea", name: "Equatorial Guinea"}, 
    { value: "Eritrea", name: "Eritrea"}, 
    { value: "Estonia", name: "Estonia"}, 
    { value: "Eswatini (formerly Swaziland)", name: "Eswatini (formerly Swaziland)"}, 
    { value: "Ethiopia", name: "Ethiopia"}, 
    { value: "Fiji", name: "Fiji"}, 
    { value: "Finland", name: "Finland"}, 
    { value: "France", name: "France"}, 
    { value: "Gabon", name: "Gabon"}, 
    { value: "Gambia", name: "Gambia"}, 
    { value: "Georgia", name: "Georgia"}, 
    { value: "Germany", name: "Germany"}, 
    { value: "Ghana", name: "Ghana"}, 
    { value: "Greece", name: "Greece"}, 
    { value: "Grenada", name: "Grenada"}, 
    { value: "Guatemala", name: "Guatemala"}, 
    { value: "Guinea", name: "Guinea"}, 
    { value: "Guinea-Bissau", name: "Guinea-Bissau"}, 
    { value: "Guyana", name: "Guyana"}, 
    { value: "Haiti", name: "Haiti"}, 
    { value: "Honduras", name: "Honduras"}, 
    { value: "Hungary", name: "Hungary"}, 
    { value: "Iceland", name: "Iceland"}, 
    { value: "India", name: "India"}, 
    { value: "Indonesia", name: "Indonesia"}, 
    { value: "Iran", name: "Iran"}, 
    { value: "Iraq", name: "Iraq"}, 
    { value: "Ireland", name: "Ireland"}, 
    { value: "Israel", name: "Israel"}, 
    { value: "Italy", name: "Italy"}, 
    { value: "Jamaica", name: "Jamaica"}, 
    { value: "Japan", name: "Japan"}, 
    { value: "Jordan", name: "Jordan"}, 
    { value: "Kazakhstan", name: "Kazakhstan"}, 
    { value: "Kenya", name: "Kenya"}, 
    { value: "Kiribati", name: "Kiribati"}, 
    { value: "Kosovo", name: "Kosovo"}, 
    { value: "Kuwait", name: "Kuwait"}, 
    { value: "Kyrgyzstan", name: "Kyrgyzstan"}, 
    { value: "Laos", name: "Laos"}, 
    { value: "Latvia", name: "Latvia"}, 
    { value: "Lebanon", name: "Lebanon"}, 
    { value: "Lesotho", name: "Lesotho"}, 
    { value: "Liberia", name: "Liberia"}, 
    { value: "Libya", name: "Libya"}, 
    { value: "Liechtenstein", name: "Liechtenstein"}, 
    { value: "Lithuania", name: "Lithuania"}, 
    { value: "Luxembourg", name: "Luxembourg"}, 
    { value: "Macedonia (FYROM)", name: "Macedonia (FYROM)"}, 
    { value: "Madagascar", name: "Madagascar"}, 
    { value: "Malawi", name: "Malawi"}, 
    { value: "Malaysia", name: "Malaysia"}, 
    { value: "Maldives", name: "Maldives"}, 
    { value: "Mali", name: "Mali"}, 
    { value: "Malta", name: "Malta"}, 
    { value: "Marshall Islands", name: "Marshall Islands"}, 
    { value: "Mauritania", name: "Mauritania"}, 
    { value: "Mauritius", name: "Mauritius"}, 
    { value: "Mexico", name: "Mexico"}, 
    { value: "Micronesia", name: "Micronesia"}, 
    { value: "Moldova", name: "Moldova"}, 
    { value: "Monaco", name: "Monaco"}, 
    { value: "Mongolia", name: "Mongolia"}, 
    { value: "Montenegro", name: "Montenegro"}, 
    { value: "Morocco", name: "Morocco"}, 
    { value: "Mozambique", name: "Mozambique"}, 
    { value: "Myanmar (formerly Burma)", name: "Myanmar (formerly Burma)"}, 
    { value: "Namibia", name: "Namibia"}, 
    { value: "Nauru", name: "Nauru"}, 
    { value: "Nepal", name: "Nepal"}, 
    { value: "Netherlands", name: "Netherlands"}, 
    { value: "New Zealand", name: "New Zealand"}, 
    { value: "Nicaragua", name: "Nicaragua"}, 
    { value: "Niger", name: "Niger"}, 
    { value: "Nigeria", name: "Nigeria"}, 
    { value: "North Korea", name: "North Korea"}, 
    { value: "Norway", name: "Norway"}, 
    { value: "Oman", name: "Oman"}, 
    { value: "Pakistan", name: "Pakistan"}, 
    { value: "Palau", name: "Palau"}, 
    { value: "Palestine", name: "Palestine"}, 
    { value: "Panama", name: "Panama"}, 
    { value: "Papua New Guinea", name: "Papua New Guinea"}, 
    { value: "Paraguay", name: "Paraguay"}, 
    { value: "Peru", name: "Peru"}, 
    { value: "Philippines", name: "Philippines"}, 
    { value: "Poland", name: "Poland"}, 
    { value: "Portugal", name: "Portugal"}, 
    { value: "Qatar", name: "Qatar"}, 
    { value: "Romania", name: "Romania"}, 
    { value: "Russia", name: "Russia"}, 
    { value: "Rwanda", name: "Rwanda"}, 
    { value: "Saint Kitts and Nevis", name: "Saint Kitts and Nevis"}, 
    { value: "Saint Lucia", name: "Saint Lucia"}, 
    { value: "Saint Vincent and the Grenadines", name: "Saint Vincent and the Grenadines"}, 
    { value: "Samoa", name: "Samoa"}, 
    { value: "San Marino", name: "San Marino"}, 
    { value: "Sao Tome and Principe", name: "Sao Tome and Principe"}, 
    { value: "Saudi Arabia", name: "Saudi Arabia"}, 
    { value: "Senegal", name: "Senegal"}, 
    { value: "Serbia", name: "Serbia"}, 
    { value: "Seychelles", name: "Seychelles"}, 
    { value: "Sierra Leone", name: "Sierra Leone"}, 
    { value: "Singapore", name: "Singapore"}, 
    { value: "Slovakia", name: "Slovakia"}, 
    { value: "Slovenia", name: "Slovenia"}, 
    { value: "Solomon Islands", name: "Solomon Islands"}, 
    { value: "Somalia", name: "Somalia"}, 
    { value: "South Africa", name: "South Africa"}, 
    { value: "South Korea", name: "South Korea"}, 
    { value: "South Sudan", name: "South Sudan"}, 
    { value: "Spain", name: "Spain"}, 
    { value: "Sri Lanka", name: "Sri Lanka"}, 
    { value: "Sudan", name: "Sudan"}, 
    { value: "Suriname", name: "Suriname"}, 
    { value: "Swaziland (renamed to Eswatini)", name: "Swaziland (renamed to Eswatini)"}, 
    { value: "Sweden", name: "Sweden"}, 
    { value: "Switzerland", name: "Switzerland"}, 
    { value: "Syria", name: "Syria"}, 
    { value: "Taiwan", name: "Taiwan"}, 
    { value: "Tajikistan", name: "Tajikistan"}, 
    { value: "Tanzania", name: "Tanzania"}, 
    { value: "Thailand", name: "Thailand"}, 
    { value: "Timor-Leste", name: "Timor-Leste"}, 
    { value: "Togo", name: "Togo"}, 
    { value: "Tonga", name: "Tonga"}, 
    { value: "Trinidad and Tobago", name: "Trinidad and Tobago"}, 
    { value: "Tunisia", name: "Tunisia"}, 
    { value: "Turkey", name: "Turkey"}, 
    { value: "Turkmenistan", name: "Turkmenistan"}, 
    { value: "Tuvalu", name: "Tuvalu"}, 
    { value: "Uganda", name: "Uganda"}, 
    { value: "Ukraine", name: "Ukraine"}, 
    { value: "United Arab Emirates", name: "United Arab Emirates"}, 
    { value: "United Kingdom", name: "United Kingdom"}, 
    { value: "United States", name: "United States"}, 
    { value: "Uruguay", name: "Uruguay"}, 
    { value: "Uzbekistan", name: "Uzbekistan"}, 
    { value: "Vanuatu", name: "Vanuatu"}, 
    { value: "Vatican City (Holy See)", name: "Vatican City (Holy See)"}, 
    { value: "Venezuela", name: "Venezuela"}, 
    { value: "Vietnam", name: "Vietnam"}, 
    { value: "Yemen", name: "Yemen"}, 
    { value: "Zambia", name: "Zambia"}, 
    { value: "Zimbabwe", name: "Zimbabwe"}, 
 ]